Chick/Controllers/KalendarzController.cs
using Chick.Logika;
using Chick.Models;
using Chick.Models.Widoki;
using Chick.ModelsViews.Kalendarz;
using Chick.ModelsViews.Kalendarz.WidokTygodnia;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chick.Controllers
{
    public class KalendarzController : Controller
    {
        ChickDbContext db = new ChickDbContext();
        Widoki w = new Widoki();

        public ActionResult DodajDanie()
        {
            var q = (from d in w.SumyDan
                     select new WyborDania
                     {
                         ID = d.ID,
                         Bialko = (double)(d.Bialko / d.Waga * 100),
                         Kalorycznosc = (double)((d.Kalorycznosc * 100) / d.Waga),
                         Klucz = d.Klucz,
                         NazwaDania = d.Nazwa,
                         Tluszcze = (double)(d.Tluszcz / d.Waga * 100),
                         Weglowodany = (double)(d.Weglowodany / d.Waga * 100)
                     }).Take(20).ToList();
            return PartialView(q);
        }


        public ActionResult SzczegolyDzien(DateTime data, string kluczDiety, string kluczDnia)
        {            
            Kalendarz k = new Kalendarz();
            List<DaniaWPosilkuPartial> daniaWPosilkuList = k.PobierzDaniaWPosilku(kluczDiety, data);
            int? UserID = UzytkownikAkcje.PobierzIDUzytkownikaZCookie();
            var q = (from daniaWPosilu in w.DaniaWPosilku
                     where daniaWPosilu.Data == data && daniaWPosilu.KluczDiety == kluczDiety && daniaWPosilu.KluczDnia == kluczDnia && daniaWPosilu.UserID == UserID
                     group daniaWPosilu by new { daniaWPosilu.Data, daniaWPosilu.NazwaPosilku, daniaWPosilu.Posilek, daniaWPosilu.KluczDnia, daniaWPosilu.KluczDiety } into g
                     orderby g.Key.Posilek
                     select new PosilkiDzienPartial()
                     {
                         NazwaPosilku = g.Key.NazwaPosilku,
                         DataStart = data,
                         DataStop = data,
                         ID = g.Key.Posilek,
                         Klucz = kluczDiety,
                         SumaBialko = (double)(g.Sum(x => x.Bialka) ?? 0),
                         SumaKalorycznosc = g.Sum(x => x.Kalorycznosc) ?? 0,
                         SumaTluszcz = (double)(g.Sum(x => x.Tluszcze) ?? 0),
                         SumaWeglowodany = (double)(g.Sum(x => x.Weglowodany) ??0)
                     }).ToList();
            return View(q);
        }

        public ActionResult WybraneDanie(string ID)
        {
            Func<decimal?, int?, double> Na100 = (makro, waga) => (100 * (double)makro) / waga ?? 100;
            Debug.Print("abc");
            WyborDania danie = w.SumyDan.Where(x => x.Klucz == ID).Select(d => new WyborDania
            {
                ID = d.ID,
                Bialko = Na100(d.Bialko, d.Waga),
                Kalorycznosc = Na100((decimal)d.Kalorycznosc,d.Waga),
                Klucz = d.Klucz,
                NazwaDania = d.Nazwa,
                Tluszcze = Na100(d.Tluszcz, d.Waga),
                Weglowodany = Na100(d.Weglowodany, d.Waga),
                Waga = 100
            }).FirstOrDefault();
            return PartialView(danie);
        }

        public JsonResult ListaDan(int strona, string k)
        {
            List<WyborDania> q = new List<WyborDania>();
            
            if (k != "")
            {
                q = WyborDania.GetAll().Where(x => x.NazwaDania.Contains(k)).ToList();
            }
            else
            {
                q = WyborDania.GetAll();
            }
            q = q.Skip((strona - 1) * 20).Take(20).ToList();
            return Json(q, JsonRequestBehavior.AllowGet);
        }
            
    }
}

Chick/Views/Kalendarz/DodajDanie.cshtml
@model IEnumerable<Chick.ModelsViews.Kalendarz.WyborDania>

@{ 
    Layout = "~/Views/Shared/Dialog.cshtml";
    ViewBag.TytulModal = "Dodaj danie do jadłospisu";
}

<div class="naglowekDialog">
    <div class="text-center przyciskiDialog mb-1">
        <a class="d-inline-block row mr-2 col-3 aktywny" href="#" role="button">
            Wszystkie
        </a>

        <a class="d-inline-block row mr-2 col-3" href="#" role="button">
            Ostatnie
        </a>

        <a class="d-inline-block row mr-2 col-3" href="#" role="button">
            Moje
        </a>
    </div>


    <input type="text" id="searchTextBox" class="searchBox d-inline mt-3 col-12 mb-2" placeholder="Wpisz nazwę dania..." onkeydown="filtruj()" />
</div>

<div class="daniaDialog" id="listaDan">
    @*@foreach (var i in Model)
    {
    <a href="@Url.Action("WybraneDanie", "Kalendarz", new { ID = i.Klucz })" data-ajax="true" data-ajax-update="#Dialog" data-ajax-mode="replace" class="danie col-12 border-bottom pt-1 pr-3 pl-3 wiersz d-block">
        <div class="col-12 row">
            @i.NazwaDania
        </div>

        <div class="col-12 row text-center">
            <div class="col-3">
                K: @i.Kalorycznosc
            </div>

            <div class="col-3">
                B: @i.Bialko
            </div>

            <div class="col-3">
                T: @i.Tluszcze
            </div>

            <div class="col-3">
                W: @i.Weglowodany
            </div>
        </div>
    </a>
    }*@
</div>

<script>
    pokazDane('');

    function pokazDane(kryteria, zeruj) {
        $.ajax({
        url: '@Url.Action("ListaDan","Kalendarz",new { strona = 1})&k=' + kryteria
        }).done(function (data) {
            if (zeruj != '') {
                $("#listaDan").html("");
            }
            $(data).each(function (index, obj) {
                $("#listaDan").append(
                    '<a href="@Url.Action("WybraneDanie", "Kalendarz")/' + obj.Klucz + '" data-ajax="true" data-ajax-update="#Dialog" data-ajax-mode="replace" class="danie col-12 border-bottom pt-1 pr-3 pl-3 wiersz d-block">' +
                        '<div class="col-12 row">' + 
                            obj.NazwaDania +
                        '</div>' +

                        '<div class="col-12 row text-center">' +
                            '<div class="col-3">' +
                                'K: ' + obj.Kalorycznosc +
                            '</div>' +
                        '</div>' +
                    '</a>'
                )
            })
        })
    }

    $("#searchTextBox").keyup(function () {
        pokazDane($(this).val(), true);
    });
</script>

Chick/Views/Kalendarz/SzczegolyDzien.cshtml
@model IEnumerable<Chick.ModelsViews.Kalendarz.WidokTygodnia.PosilkiDzienPartial>

@{
    ViewBag.Title = "SzczegolyDzien";
}

@foreach (var i in Model)
{
    @i.DataStart;

    foreach (var j in i.DaniaWPosilku)
    {
        @j.NazwaDania
    }

}

Chick/Views/Kalendarz/WybraneDanie.cshtml
@model Chick.ModelsViews.Kalendarz.WyborDania

@{
    Layout = "~/Views/Shared/Dialog.cshtml";
    ViewBag.TytulModal = Model.NazwaDania;
}

<div class="row">
    <div class="col-6" id="wykresSkladniki" style="height: 200px;">
        Tu będzie wykres
    </div>
    <div class="col-6">
        <div class="row">
            @Html.LabelFor(x => x.Waga)
            @Html.EditorFor(x => x.Waga, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="row">
            <div class="col">
                Kaloryczność @Html.DisplayFor(x => x.Kalorycznosc)
            </div>
            <div class="col">
                Białko @Html.DisplayFor(x => x.Bialko)
            </div>
            <div class="col">
                Tłuszcz @Html.DisplayFor(x => x.Tluszcze)
            </div>
            <div class="col">

                Węgl @Html.DisplayFor(x => x.Weglowodany)
            </div>
        </div>
    </div>
</div>

<script>
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Language', 'Speakers (in millions)'],
            ['Białko', @Model.Bialko.ToString().Replace(',','.')],
            ['Tłuszcz', @Model.Tluszcze.ToString().Replace(',', '.')],
            ['Węgl', @Model.Weglowodany.ToString().Replace(',', '.')]
        ]);

        var options = {
            legend: 'none',
            pieSliceText: 'label',
            pieStartAngle: 100,
            tooltip: { trigger: 'none' },
            slices: {
                0: { color: '#2196f3' },
                1: { color: '#a59d52' },
                2: { color: '#795548'}
            }
        };

        var chart = new google.visualization.PieChart(document.getElementById('wykresSkladniki'));
        chart.draw(data, options);
    }
</script>