Chick/Controllers/PanelController.cs
using Chick.Logika;
using Chick.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chick.Controllers
{
    public class PanelController : Controller
    {
        static ChickDbContext db = new ChickDbContext();

        public ActionResult Klienci()
        {
            int? UzytkownikID = UzytkownikAkcje.PobierzIDUzytkownikaZCookie();
            var q = db.Pacjenci.Where(x => x.Dietetyk == UzytkownikID).Select(x => x.Nazwisko).ToList();
            return Json(q, JsonRequestBehavior.AllowGet);
        }


        public ActionResult LeweMenu()
        {
            
            return PartialView();
        }

        public ActionResult Naglowek(string Naglowek)
        {
            var q = UzytkownikAkcje.PobierzUzytkownikaZCookie();
            ViewBag.uzytkownik = $"{q.Imie} {q.Nazwisko}";
            return PartialView();
        }
    }
}

Chick/Views/Shared/Dialog.cshtml
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">@ViewBag.TytulModal</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        @using (Html.BeginForm((string)ViewBag.Akcja, (string)ViewBag.Kontroler)) {
        
            <div class="modal-body modal-moj">
                @RenderBody()
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">@ViewBag.BtnZamknij</button>
                <button type="submit" class="btn btn-primary">@ViewBag.BtnWyslij</button>
            </div>
        }
    </div>
</div>

Chick/Views/Shared/Naglowek.cshtml
@{
    Layout = null;
}

<div class="naglowek pt-2 pb-1 shadow">
    <div class="row">
        <a class="navbar-brand col-1 row text-center logo">
            <img src="~/Images/logo.png" height="30" />
        </a>

        <div class="col-2 row">
            <input type="text" id="szukaniePacjenta" class="searchBox" placeholder="Szukaj pacjenta..." />
        </div>

        <div class="text-center col-7 text-white font-weight-bold">@ViewBag.Tytul</div>
        <div class="col-2 text-right">
            <a href="#">
                <i class="icon-user"></i> @ViewBag.uzytkownik
            </a>
        </div>
    </div>
</div>

<script>
    var d;
    $.getJSON("@Url.Action("Klienci","Panel")", function (json) {
        d = json;
    })

    $(document).ready(function () {
        $("#szukaniePacjenta").autocomplete({source: d})
    })
</script>

Chick/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Chick/Views/Shared/_Panel.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Tytul - Chick</title>
    <link href="~/Content/wspolne.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="~/css/fontello.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet">
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>
<body>
    <div id="naglowek">
        @{ 
            Html.RenderAction("Naglowek", "Panel");
        }
    </div>

    <div id="leweMenu">
        @{
            Html.RenderAction("LeweMenu","Panel");
        }
    </div>

    <div id="zawartosc" class="offset-2 col-10 mt-3 h-100 position-fixed text-secondary">
        @RenderBody()
    </div>

    <div id="Dialog" class="modal fade" tabindex="-1" role="dialog">
        @{ 

        }
    </div>

    <div id="PrawyPanel">

    </div>
</body>
</html>